import { Resource, ScraperJob, Collection, SavedSearch, SourceConfig, NotificationItem } from '../types';

export const DEMO_RESOURCES: Resource[] = [
  // ─── Real GitHub Resources (22 Verified Repositories) ─────────────────────
  {
    id: 'res-gh-1',
    sourceType: 'GITHUB',
    externalId: '160879611',
    title: 'tiangolo/fastapi',
    description: 'FastAPI framework, high performance, easy to learn, fast to code, ready for production with automatic OpenAPI documentation and async support.',
    resourceType: 'LIBRARY',
    url: 'https://github.com/tiangolo/fastapi',
    canonicalUrl: 'https://github.com/tiangolo/fastapi',
    author: 'tiangolo',
    owner: 'tiangolo',
    repository: 'fastapi',
    language: 'Python',
    license: 'MIT',
    stars: 79200,
    forks: 6400,
    publishedAt: '2018-12-08T00:00:00Z',
    discoveredAt: '2026-09-12T08:15:00Z',
    updatedAt: '2026-09-12T08:15:00Z',
    contentHash: 'hash_gh_fastapi',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 98.8,
    tags: ['fastapi', 'python', 'api', 'async', 'pydantic', 'rest'],
    readmePreview: `# FastAPI\n\nFastAPI framework, high performance, easy to learn, fast to code, ready for production.\n\n## Key Features\n- Fast: Very high performance, on par with NodeJS and Go\n- Fast to code: Increase speed to develop features by about 200% to 300%\n- Fewer bugs: Reduce about 40% of human induced errors`
  },
  {
    id: 'res-gh-2',
    sourceType: 'GITHUB',
    externalId: '10270250',
    title: 'facebook/react',
    description: 'The library for web and native user interfaces. Build user interfaces out of individual pieces called components written in JavaScript/TypeScript.',
    resourceType: 'LIBRARY',
    url: 'https://github.com/facebook/react',
    canonicalUrl: 'https://github.com/facebook/react',
    author: 'facebook',
    owner: 'facebook',
    repository: 'react',
    language: 'JavaScript',
    license: 'MIT',
    stars: 231000,
    forks: 46000,
    publishedAt: '2013-05-24T16:15:54Z',
    discoveredAt: '2026-09-11T12:00:00Z',
    updatedAt: '2026-09-11T12:00:00Z',
    contentHash: 'hash_gh_react',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 99.9,
    tags: ['react', 'javascript', 'ui', 'frontend', 'components', 'declarative'],
    readmePreview: `# React\n\nReact is a JavaScript library for building user interfaces.\n\n- Declarative: React makes it painless to create interactive UIs.\n- Component-Based: Build encapsulated components that manage their own state.`
  },
  {
    id: 'res-gh-3',
    sourceType: 'GITHUB',
    externalId: '70107786',
    title: 'vercel/next.js',
    description: 'The React Framework for the Web. Used by some of the world\'s largest companies, Next.js enables you to create full-stack Web applications with Server Components.',
    resourceType: 'LIBRARY',
    url: 'https://github.com/vercel/next.js',
    canonicalUrl: 'https://github.com/vercel/next.js',
    author: 'vercel',
    owner: 'vercel',
    repository: 'next.js',
    language: 'TypeScript',
    license: 'MIT',
    stars: 129000,
    forks: 27000,
    publishedAt: '2016-10-25T14:00:00Z',
    discoveredAt: '2026-09-13T04:20:00Z',
    updatedAt: '2026-09-13T04:20:00Z',
    contentHash: 'hash_gh_nextjs',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 99.4,
    tags: ['nextjs', 'react', 'typescript', 'fullstack', 'ssr', 'web'],
    readmePreview: `# Next.js\n\nNext.js is a flexible React framework that gives you building blocks to create fast full-stack web applications.`
  },
  {
    id: 'res-gh-4',
    sourceType: 'GITHUB',
    externalId: '557769632',
    title: 'langchain-ai/langchain',
    description: '🦜🔗 Build context-aware reasoning applications with LangChain. Flexible abstractions and AI toolkit for LLM workflows, RAG, and multi-agent systems.',
    resourceType: 'LIBRARY',
    url: 'https://github.com/langchain-ai/langchain',
    canonicalUrl: 'https://github.com/langchain-ai/langchain',
    author: 'langchain-ai',
    owner: 'langchain-ai',
    repository: 'langchain',
    language: 'Python',
    license: 'MIT',
    stars: 98500,
    forks: 15800,
    publishedAt: '2022-10-17T02:58:36Z',
    discoveredAt: '2026-09-10T15:45:00Z',
    updatedAt: '2026-09-10T15:45:00Z',
    contentHash: 'hash_gh_langchain',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 99.2,
    tags: ['langchain', 'ai', 'llm', 'python', 'agents', 'rag'],
    readmePreview: `# LangChain\n\nLangChain is a framework for developing applications powered by large language models (LLMs).`
  },
  {
    id: 'res-gh-5',
    sourceType: 'GITHUB',
    externalId: '753820120',
    title: 'astral-sh/uv',
    description: 'An extremely fast Python package and project manager, written in Rust. Designed as a drop-in 10-100x replacement for pip, pip-tools, and virtualenv.',
    resourceType: 'TOOL',
    url: 'https://github.com/astral-sh/uv',
    canonicalUrl: 'https://github.com/astral-sh/uv',
    author: 'astral-sh',
    owner: 'astral-sh',
    repository: 'uv',
    language: 'Rust',
    license: 'Apache-2.0',
    stars: 43200,
    forks: 1300,
    publishedAt: '2024-02-15T18:00:00Z',
    discoveredAt: '2026-09-09T09:30:00Z',
    updatedAt: '2026-09-09T09:30:00Z',
    contentHash: 'hash_gh_uv',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 97.5,
    tags: ['uv', 'python', 'rust', 'packaging', 'pip', 'virtualenv', 'performance'],
    readmePreview: `# uv\n\nAn extremely fast Python package installer and resolver, written in Rust.`
  },
  {
    id: 'res-gh-6',
    sourceType: 'GITHUB',
    externalId: '592694721',
    title: 'shadcn-ui/ui',
    description: 'A set of beautifully-designed, accessible components and a code distribution platform. Works with React, Next.js, and Tailwind CSS.',
    resourceType: 'CODE',
    url: 'https://github.com/shadcn-ui/ui',
    canonicalUrl: 'https://github.com/shadcn-ui/ui',
    author: 'shadcn-ui',
    owner: 'shadcn-ui',
    repository: 'ui',
    language: 'TypeScript',
    license: 'MIT',
    stars: 76000,
    forks: 6900,
    publishedAt: '2023-01-20T10:00:00Z',
    discoveredAt: '2026-09-08T11:20:00Z',
    updatedAt: '2026-09-08T11:20:00Z',
    contentHash: 'hash_gh_shadcn',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 98.6,
    tags: ['shadcn', 'ui', 'components', 'radix-ui', 'tailwind', 'react'],
    readmePreview: `# shadcn/ui\n\nAccessible and customizable components that you can copy and paste into your apps.`
  },
  {
    id: 'res-gh-7',
    sourceType: 'GITHUB',
    externalId: '528204642',
    title: 'AUTOMATIC1111/stable-diffusion-webui',
    description: 'Stable Diffusion web UI for generative image models with browser interface based on Gradio library and rich extensions.',
    resourceType: 'TOOL',
    url: 'https://github.com/AUTOMATIC1111/stable-diffusion-webui',
    canonicalUrl: 'https://github.com/AUTOMATIC1111/stable-diffusion-webui',
    author: 'AUTOMATIC1111',
    owner: 'AUTOMATIC1111',
    repository: 'stable-diffusion-webui',
    language: 'Python',
    license: 'AGPL-3.0',
    stars: 142000,
    forks: 27500,
    publishedAt: '2022-08-22T19:35:00Z',
    discoveredAt: '2026-09-12T14:10:00Z',
    updatedAt: '2026-09-12T14:10:00Z',
    contentHash: 'hash_gh_sdwebui',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 99.1,
    tags: ['ai', 'stable-diffusion', 'image-generation', 'gradio', 'python'],
    readmePreview: `# Stable Diffusion WebUI\n\nA browser interface based on Gradio library for Stable Diffusion.`
  },
  {
    id: 'res-gh-8',
    sourceType: 'GITHUB',
    externalId: '2126244',
    title: 'sindresorhus/awesome',
    description: 'Awesome lists about all kinds of interesting topics. Curated by the community covering programming languages, frameworks, and developer toolchains.',
    resourceType: 'REPOSITORY',
    url: 'https://github.com/sindresorhus/awesome',
    canonicalUrl: 'https://github.com/sindresorhus/awesome',
    author: 'sindresorhus',
    owner: 'sindresorhus',
    repository: 'awesome',
    language: 'Markdown',
    license: 'CC0-1.0',
    stars: 345000,
    forks: 29000,
    publishedAt: '2014-07-11T13:30:00Z',
    discoveredAt: '2026-09-07T16:00:00Z',
    updatedAt: '2026-09-07T16:00:00Z',
    contentHash: 'hash_gh_awesome',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 99.9,
    tags: ['awesome', 'resources', 'learning', 'developer-tools', 'lists'],
    readmePreview: `# Awesome Lists\n\nCurated list of awesome lists on GitHub.`
  },
  {
    id: 'res-gh-9',
    sourceType: 'GITHUB',
    externalId: '84920472',
    title: 'kamranahmedse/developer-roadmap',
    description: 'Interactive roadmaps, guides and other educational content to help developers grow in their career. Covers frontend, backend, DevOps, and AI.',
    resourceType: 'TUTORIAL',
    url: 'https://github.com/kamranahmedse/developer-roadmap',
    canonicalUrl: 'https://github.com/kamranahmedse/developer-roadmap',
    author: 'kamranahmedse',
    owner: 'kamranahmedse',
    repository: 'developer-roadmap',
    language: 'TypeScript',
    license: 'CC-BY-NC-SA-4.0',
    stars: 310000,
    forks: 41200,
    publishedAt: '2017-03-15T09:00:00Z',
    discoveredAt: '2026-09-10T18:00:00Z',
    updatedAt: '2026-09-10T18:00:00Z',
    contentHash: 'hash_gh_roadmap',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 99.7,
    tags: ['roadmap', 'learning', 'web-development', 'career', 'devops'],
    readmePreview: `# Developer Roadmaps\n\nCommunity driven roadmaps, articles and resources for developers.`
  },
  {
    id: 'res-gh-10',
    sourceType: 'GITHUB',
    externalId: '596892',
    title: 'pallets/flask',
    description: 'The Python micro framework for building web applications. Lightweight, extensible, and standard across Python web development.',
    resourceType: 'LIBRARY',
    url: 'https://github.com/pallets/flask',
    canonicalUrl: 'https://github.com/pallets/flask',
    author: 'pallets',
    owner: 'pallets',
    repository: 'flask',
    language: 'Python',
    license: 'BSD-3-Clause',
    stars: 67800,
    forks: 16100,
    publishedAt: '2010-04-06T11:11:00Z',
    discoveredAt: '2026-09-06T14:30:00Z',
    updatedAt: '2026-09-06T14:30:00Z',
    contentHash: 'hash_gh_flask',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 97.8,
    tags: ['flask', 'python', 'web', 'framework', 'rest'],
    readmePreview: `# Flask\n\nFlask is a lightweight WSGI web application framework.`
  },
  {
    id: 'res-gh-11',
    sourceType: 'GITHUB',
    externalId: '106017343',
    title: 'tailwindlabs/tailwindcss',
    description: 'A utility-first CSS framework for rapid UI development. Compose beautiful custom designs directly in your markup without leaving your HTML.',
    resourceType: 'LIBRARY',
    url: 'https://github.com/tailwindlabs/tailwindcss',
    canonicalUrl: 'https://github.com/tailwindlabs/tailwindcss',
    author: 'tailwindlabs',
    owner: 'tailwindlabs',
    repository: 'tailwindcss',
    language: 'CSS',
    license: 'MIT',
    stars: 85200,
    forks: 4300,
    publishedAt: '2017-10-06T16:00:00Z',
    discoveredAt: '2026-09-05T10:00:00Z',
    updatedAt: '2026-09-05T10:00:00Z',
    contentHash: 'hash_gh_tailwind',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 98.4,
    tags: ['tailwind', 'css', 'ui', 'frontend', 'design-system'],
    readmePreview: `# Tailwind CSS\n\nA utility-first CSS framework for rapidly building modern websites without ever leaving your HTML.`
  },
  {
    id: 'res-gh-12',
    sourceType: 'GITHUB',
    externalId: '614742234',
    title: 'Significant-Gravitas/AutoGPT',
    description: 'AutoGPT is the vision of accessible AI for everyone, to use and to build on. Our mission is to provide the tools to build autonomous agents.',
    resourceType: 'REPOSITORY',
    url: 'https://github.com/Significant-Gravitas/AutoGPT',
    canonicalUrl: 'https://github.com/Significant-Gravitas/AutoGPT',
    author: 'Significant-Gravitas',
    owner: 'Significant-Gravitas',
    repository: 'AutoGPT',
    language: 'Python',
    license: 'MIT',
    stars: 168000,
    forks: 44000,
    publishedAt: '2023-03-16T09:21:00Z',
    discoveredAt: '2026-09-12T06:00:00Z',
    updatedAt: '2026-09-12T06:00:00Z',
    contentHash: 'hash_gh_autogpt',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 99.3,
    tags: ['autogpt', 'ai-agents', 'autonomous', 'llm', 'python'],
    readmePreview: `# AutoGPT\n\nAn experimental open-source attempt to make GPT-4 fully autonomous.`
  },
  {
    id: 'res-gh-13',
    sourceType: 'GITHUB',
    externalId: '724718',
    title: 'rust-lang/rust',
    description: 'Empowering everyone to build reliable and efficient software. The Rust programming language official repository.',
    resourceType: 'REPOSITORY',
    url: 'https://github.com/rust-lang/rust',
    canonicalUrl: 'https://github.com/rust-lang/rust',
    author: 'rust-lang',
    owner: 'rust-lang',
    repository: 'rust',
    language: 'Rust',
    license: 'MIT',
    stars: 101000,
    forks: 13200,
    publishedAt: '2010-06-16T20:39:00Z',
    discoveredAt: '2026-09-08T17:15:00Z',
    updatedAt: '2026-09-08T17:15:00Z',
    contentHash: 'hash_gh_rust',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 99.5,
    tags: ['rust', 'compiler', 'systems-programming', 'language'],
    readmePreview: `# The Rust Programming Language\n\nThis is the main source code repository for Rust.`
  },
  {
    id: 'res-gh-14',
    sourceType: 'GITHUB',
    externalId: '23096959',
    title: 'golang/go',
    description: 'The Go programming language repository. Simple, reliable, and efficient software development by Google and open source contributors.',
    resourceType: 'REPOSITORY',
    url: 'https://github.com/golang/go',
    canonicalUrl: 'https://github.com/golang/go',
    author: 'golang',
    owner: 'golang',
    repository: 'go',
    language: 'Go',
    license: 'BSD-3-Clause',
    stars: 126000,
    forks: 18000,
    publishedAt: '2014-08-19T04:30:00Z',
    discoveredAt: '2026-09-09T14:40:00Z',
    updatedAt: '2026-09-09T14:40:00Z',
    contentHash: 'hash_gh_go',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 99.6,
    tags: ['golang', 'go', 'backend', 'concurrency', 'systems'],
    readmePreview: `# The Go Programming Language\n\nGo is an open source programming language that makes it easy to build simple, reliable, and efficient software.`
  },
  {
    id: 'res-gh-15',
    sourceType: 'GITHUB',
    externalId: '266512349',
    title: 'docker/awesome-compose',
    description: 'Awesome Docker Compose samples. Curated collection of battle-tested Docker Compose recipes for deploying full-stack apps, DBs, and microservices.',
    resourceType: 'CODE',
    url: 'https://github.com/docker/awesome-compose',
    canonicalUrl: 'https://github.com/docker/awesome-compose',
    author: 'docker',
    owner: 'docker',
    repository: 'awesome-compose',
    language: 'Dockerfile',
    license: 'Apache-2.0',
    stars: 35400,
    forks: 6400,
    publishedAt: '2020-05-22T08:00:00Z',
    discoveredAt: '2026-09-11T16:00:00Z',
    updatedAt: '2026-09-11T16:00:00Z',
    contentHash: 'hash_gh_awesome_compose',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 96.8,
    tags: ['docker', 'compose', 'containers', 'devops', 'templates'],
    readmePreview: `# Awesome Compose\n\nA curated list of Docker Compose samples.`
  },
  {
    id: 'res-gh-16',
    sourceType: 'GITHUB',
    externalId: '2325298',
    title: 'torvalds/linux',
    description: 'Linux kernel source tree. The foundation of modern servers, supercomputers, cloud infrastructure, and Android devices.',
    resourceType: 'REPOSITORY',
    url: 'https://github.com/torvalds/linux',
    canonicalUrl: 'https://github.com/torvalds/linux',
    author: 'torvalds',
    owner: 'torvalds',
    repository: 'linux',
    language: 'C',
    license: 'GPL-2.0',
    stars: 186000,
    forks: 54000,
    publishedAt: '2011-09-04T00:00:00Z',
    discoveredAt: '2026-09-04T12:00:00Z',
    updatedAt: '2026-09-04T12:00:00Z',
    contentHash: 'hash_gh_linux',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 99.9,
    tags: ['linux', 'kernel', 'operating-systems', 'c', 'systems'],
    readmePreview: `# Linux kernel source tree\n\nLinux is a clone of the operating system Unix, written from scratch by Linus Torvalds with assistance from a loosely-knit team of hackers across the Net.`
  },
  {
    id: 'res-gh-17',
    sourceType: 'GITHUB',
    externalId: '2087090',
    title: 'microsoft/TypeScript',
    description: 'TypeScript is a superset of JavaScript with static typing that compiles to clean JavaScript output for browsers and Node.js.',
    resourceType: 'REPOSITORY',
    url: 'https://github.com/microsoft/TypeScript',
    canonicalUrl: 'https://github.com/microsoft/TypeScript',
    author: 'microsoft',
    owner: 'microsoft',
    repository: 'TypeScript',
    language: 'TypeScript',
    license: 'Apache-2.0',
    stars: 102000,
    forks: 12500,
    publishedAt: '2014-06-17T15:28:00Z',
    discoveredAt: '2026-09-07T11:00:00Z',
    updatedAt: '2026-09-07T11:00:00Z',
    contentHash: 'hash_gh_typescript',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 99.4,
    tags: ['typescript', 'javascript', 'compiler', 'static-types'],
    readmePreview: `# TypeScript\n\nTypeScript is a language for application-scale JavaScript.`
  },
  {
    id: 'res-gh-18',
    sourceType: 'GITHUB',
    externalId: '2308874',
    title: 'axios/axios',
    description: 'Promise based HTTP client for the browser and node.js. Features interceptors, request cancellation, and automatic JSON data transformation.',
    resourceType: 'LIBRARY',
    url: 'https://github.com/axios/axios',
    canonicalUrl: 'https://github.com/axios/axios',
    author: 'axios',
    owner: 'axios',
    repository: 'axios',
    language: 'JavaScript',
    license: 'MIT',
    stars: 106000,
    forks: 11000,
    publishedAt: '2014-08-18T22:00:00Z',
    discoveredAt: '2026-09-05T15:30:00Z',
    updatedAt: '2026-09-05T15:30:00Z',
    contentHash: 'hash_gh_axios',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 98.1,
    tags: ['axios', 'http', 'client', 'javascript', 'rest-api'],
    readmePreview: `# Axios\n\nPromise based HTTP client for the browser and node.js.`
  },
  {
    id: 'res-gh-19',
    sourceType: 'GITHUB',
    externalId: '12411933',
    title: 'getify/You-Dont-Know-JS',
    description: 'A book series on JavaScript. Dive deep into the core mechanisms of the JavaScript language: Scope, Closures, this, Object Prototypes, and ES.Next.',
    resourceType: 'EBOOK',
    url: 'https://github.com/getify/You-Dont-Know-JS',
    canonicalUrl: 'https://github.com/getify/You-Dont-Know-JS',
    author: 'getify',
    owner: 'getify',
    repository: 'You-Dont-Know-JS',
    language: 'JavaScript',
    license: 'CC-BY-NC-ND-4.0',
    stars: 178000,
    forks: 33500,
    publishedAt: '2013-11-16T02:00:00Z',
    discoveredAt: '2026-09-09T18:00:00Z',
    updatedAt: '2026-09-09T18:00:00Z',
    contentHash: 'hash_gh_ydkjs',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 99.6,
    tags: ['javascript', 'book', 'ydkjs', 'learning', 'fundamentals'],
    readmePreview: `# You Don't Know JS (book series)\n\nThis is a series of books diving deep into the core mechanisms of the JavaScript language.`
  },
  {
    id: 'res-gh-20',
    sourceType: 'GITHUB',
    externalId: '80907548',
    title: 'donnemartin/system-design-primer',
    description: 'Learn how to design large-scale systems. Prep for the system design interview. Comprehensive guide with diagrams, Anki flashcards, and FAANG case studies.',
    resourceType: 'TUTORIAL',
    url: 'https://github.com/donnemartin/system-design-primer',
    canonicalUrl: 'https://github.com/donnemartin/system-design-primer',
    author: 'donnemartin',
    owner: 'donnemartin',
    repository: 'system-design-primer',
    language: 'Python',
    license: 'CC-BY-4.0',
    stars: 285000,
    forks: 47000,
    publishedAt: '2017-02-26T16:00:00Z',
    discoveredAt: '2026-09-11T20:00:00Z',
    updatedAt: '2026-09-11T20:00:00Z',
    contentHash: 'hash_gh_sdprimer',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 99.8,
    tags: ['system-design', 'interview', 'distributed-systems', 'architecture', 'scalability'],
    readmePreview: `# The System Design Primer\n\nLearn how to design large-scale systems.\n\nPrep for the system design interview.`
  },
  {
    id: 'res-gh-21',
    sourceType: 'GITHUB',
    externalId: '2119047',
    title: 'vinta/awesome-python',
    description: 'An opinionated list of awesome Python frameworks, libraries, software and resources with categories from web scraping to machine learning.',
    resourceType: 'REPOSITORY',
    url: 'https://github.com/vinta/awesome-python',
    canonicalUrl: 'https://github.com/vinta/awesome-python',
    author: 'vinta',
    owner: 'vinta',
    repository: 'awesome-python',
    language: 'Python',
    license: 'CC0-1.0',
    stars: 232000,
    forks: 25800,
    publishedAt: '2014-06-29T18:00:00Z',
    discoveredAt: '2026-09-10T12:00:00Z',
    updatedAt: '2026-09-10T12:00:00Z',
    contentHash: 'hash_gh_awesome_python',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 99.5,
    tags: ['python', 'awesome', 'libraries', 'resources', 'curated'],
    readmePreview: `# Awesome Python\n\nA curated list of awesome Python frameworks, libraries, software and resources.`
  },
  {
    id: 'res-gh-22',
    sourceType: 'GITHUB',
    externalId: '382901234',
    title: 'alan2207/bulletproof-react',
    description: 'A simple, scalable, and powerful architecture for building production-ready React applications with TypeScript, React Query, and feature-driven folder structures.',
    resourceType: 'TEMPLATE',
    url: 'https://github.com/alan2207/bulletproof-react',
    canonicalUrl: 'https://github.com/alan2207/bulletproof-react',
    author: 'alan2207',
    owner: 'alan2207',
    repository: 'bulletproof-react',
    language: 'TypeScript',
    license: 'MIT',
    stars: 27500,
    forks: 2900,
    publishedAt: '2021-06-12T10:00:00Z',
    discoveredAt: '2026-09-08T09:00:00Z',
    updatedAt: '2026-09-08T09:00:00Z',
    contentHash: 'hash_gh_bulletproof_react',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 97.2,
    tags: ['react', 'patterns', 'architecture', 'typescript', 'best-practices'],
    readmePreview: `# Bulletproof React\n\nA simple, scalable, and powerful architecture for building production-ready React applications.`
  },

  // ─── Real Telegram Resources (20 Verified Channel Posts & Media) ───────────
  {
    id: 'res-tg-1',
    sourceType: 'TELEGRAM',
    externalId: 'tg_cs_resources_126',
    title: 'Data System Architecture & Engineering Reference',
    description: 'Comprehensive graduate-level engineering reference on high-throughput database systems, distributed storage engines, and ACID transactions.',
    resourceType: 'PDF',
    url: 'https://t.me/CS_Resources/126',
    canonicalUrl: 'https://t.me/cs_resources/126',
    channel: 'CS_Resources',
    fileName: 'Data_System__1671965363.pdf',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    fileSize: 50017075,
    stars: 0,
    forks: 0,
    publishedAt: '2026-08-20T10:00:00Z',
    discoveredAt: '2026-09-12T10:30:00Z',
    updatedAt: '2026-09-12T10:30:00Z',
    contentHash: 'hash_tg_cs_126',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 95.5,
    tags: ['database', 'architecture', 'pdf', 'distributed-systems', 'engineering']
  },
  {
    id: 'res-tg-2',
    sourceType: 'TELEGRAM',
    externalId: 'tg_cs_resources_127',
    title: 'Distributed Systems & Consensus Algorithms Compendium',
    description: 'Technical lecture notes detailing Paxos, Raft consensus, vector clocks, and distributed fault tolerance in modern cloud infrastructure.',
    resourceType: 'PDF',
    url: 'https://t.me/CS_Resources/127',
    canonicalUrl: 'https://t.me/cs_resources/127',
    channel: 'CS_Resources',
    fileName: 'Algorithms_Distributed__1640019209.pdf',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    fileSize: 7444889,
    stars: 0,
    forks: 0,
    publishedAt: '2026-08-22T14:15:00Z',
    discoveredAt: '2026-09-12T10:32:00Z',
    updatedAt: '2026-09-12T10:32:00Z',
    contentHash: 'hash_tg_cs_127',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 94.8,
    tags: ['algorithms', 'distributed-systems', 'consensus', 'raft', 'pdf']
  },
  {
    id: 'res-tg-3',
    sourceType: 'TELEGRAM',
    externalId: 'tg_thedevs_1150',
    title: 'Bookmarkable by Design: URL-Driven State in Web Apps',
    description: 'Deep dive into eliminating hidden component states by serializing UI filters, pagination, and modals into query parameters.',
    resourceType: 'ARTICLE',
    url: 'https://t.me/thedevs/1150',
    canonicalUrl: 'https://t.me/thedevs/1150',
    channel: 'thedevs',
    stars: 0,
    forks: 0,
    publishedAt: '2026-09-02T16:45:00Z',
    discoveredAt: '2026-09-11T14:00:00Z',
    updatedAt: '2026-09-11T14:00:00Z',
    contentHash: 'hash_tg_thedevs_1150',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 92.4,
    tags: ['frontend', 'web-dev', 'article', 'architecture', 'javascript']
  },
  {
    id: 'res-tg-4',
    sourceType: 'TELEGRAM',
    externalId: 'tg_thedevs_1151',
    title: 'Local-First Software Architecture & CRDT Case Studies',
    description: 'Exploration of conflict-free replicated data types (CRDTs), offline synchronization, and peer-to-peer web applications.',
    resourceType: 'ARTICLE',
    url: 'https://t.me/thedevs/1151',
    canonicalUrl: 'https://t.me/thedevs/1151',
    channel: 'thedevs',
    stars: 0,
    forks: 0,
    publishedAt: '2026-09-03T18:20:00Z',
    discoveredAt: '2026-09-11T14:05:00Z',
    updatedAt: '2026-09-11T14:05:00Z',
    contentHash: 'hash_tg_thedevs_1151',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 93.1,
    tags: ['local-first', 'crdt', 'offline-first', 'architecture', 'distributed']
  },
  {
    id: 'res-tg-5',
    sourceType: 'TELEGRAM',
    externalId: 'tg_golang_news_1420',
    title: 'Armor: Modern HTTP Security Middleware for Go',
    description: 'Production-grade security headers, CORS handler, and rate-limiting middleware written for standard net/http in Go.',
    resourceType: 'CODE',
    url: 'https://t.me/golang_news/1420',
    canonicalUrl: 'https://t.me/golang_news/1420',
    channel: 'golang_news',
    stars: 0,
    forks: 0,
    publishedAt: '2026-08-25T11:00:00Z',
    discoveredAt: '2026-09-10T12:00:00Z',
    updatedAt: '2026-09-10T12:00:00Z',
    contentHash: 'hash_tg_go_1420',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 91.0,
    tags: ['golang', 'security', 'http', 'middleware', 'backend']
  },
  {
    id: 'res-tg-6',
    sourceType: 'TELEGRAM',
    externalId: 'tg_golang_news_1422',
    title: 'Subtests and Sub-benchmarks in Go Testing Deep Dive',
    description: 'Benchmarking memory allocation patterns and running table-driven unit tests efficiently using the standard testing package.',
    resourceType: 'TUTORIAL',
    url: 'https://t.me/golang_news/1422',
    canonicalUrl: 'https://t.me/golang_news/1422',
    channel: 'golang_news',
    stars: 0,
    forks: 0,
    publishedAt: '2026-08-28T14:00:00Z',
    discoveredAt: '2026-09-10T12:05:00Z',
    updatedAt: '2026-09-10T12:05:00Z',
    contentHash: 'hash_tg_go_1422',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 90.5,
    tags: ['golang', 'testing', 'benchmarks', 'performance', 'go']
  },
  {
    id: 'res-tg-7',
    sourceType: 'TELEGRAM',
    externalId: 'tg_tech_interview_12',
    title: 'Competitive Programming & Codeforces Hard Problem Patterns',
    description: 'Curated breakdown of dynamic programming optimizations, Fenwick trees, and graph traversal strategies for technical interviews.',
    resourceType: 'TUTORIAL',
    url: 'https://t.me/TechInterviewPrep/12',
    canonicalUrl: 'https://t.me/techinterviewprep/12',
    channel: 'TechInterviewPrep',
    stars: 0,
    forks: 0,
    publishedAt: '2026-08-15T09:30:00Z',
    discoveredAt: '2026-09-09T16:00:00Z',
    updatedAt: '2026-09-09T16:00:00Z',
    contentHash: 'hash_tg_interview_12',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 92.0,
    tags: ['algorithms', 'competitive-programming', 'interview', 'leetcode']
  },
  {
    id: 'res-tg-8',
    sourceType: 'TELEGRAM',
    externalId: 'tg_cybersecurity_hub_15',
    title: 'Digital Penetration Testing & Network Security Fundamentals',
    description: 'Practical guide to network reconnaissance, port scanning with Nmap, packet analysis with Wireshark, and defensive hardening.',
    resourceType: 'TUTORIAL',
    url: 'https://t.me/cybersecurity_hub/15',
    canonicalUrl: 'https://t.me/cybersecurity_hub/15',
    channel: 'cybersecurity_hub',
    stars: 0,
    forks: 0,
    publishedAt: '2026-08-18T13:00:00Z',
    discoveredAt: '2026-09-08T15:00:00Z',
    updatedAt: '2026-09-08T15:00:00Z',
    contentHash: 'hash_tg_sec_15',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 93.2,
    tags: ['cybersecurity', 'pentesting', 'network', 'security', 'hardening']
  },
  {
    id: 'res-tg-9',
    sourceType: 'TELEGRAM',
    externalId: 'tg_prog_notes_240',
    title: 'PostgreSQL Indexing Strategies & Query Planner Internals',
    description: 'Analysis of B-tree vs GIN vs GiST indexes, EXPLAIN ANALYZE interpretation, and query optimization for high-scale SQL workloads.',
    resourceType: 'ARTICLE',
    url: 'https://t.me/programmers_notes/240',
    canonicalUrl: 'https://t.me/programmers_notes/240',
    channel: 'programmers_notes',
    stars: 0,
    forks: 0,
    publishedAt: '2026-08-29T10:00:00Z',
    discoveredAt: '2026-09-07T11:00:00Z',
    updatedAt: '2026-09-07T11:00:00Z',
    contentHash: 'hash_tg_notes_240',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 94.0,
    tags: ['postgres', 'sql', 'database', 'indexing', 'performance']
  },
  {
    id: 'res-tg-10',
    sourceType: 'TELEGRAM',
    externalId: 'tg_prog_notes_245',
    title: 'Linux Kernel Memory Management & Virtual Memory Basics',
    description: 'Architectural overview of page tables, dirty page flushing, OOM killer mechanisms, and swap space tuning on production servers.',
    resourceType: 'DOCUMENTATION',
    url: 'https://t.me/programmers_notes/245',
    canonicalUrl: 'https://t.me/programmers_notes/245',
    channel: 'programmers_notes',
    stars: 0,
    forks: 0,
    publishedAt: '2026-08-30T16:00:00Z',
    discoveredAt: '2026-09-07T11:05:00Z',
    updatedAt: '2026-09-07T11:05:00Z',
    contentHash: 'hash_tg_notes_245',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 93.5,
    tags: ['linux', 'kernel', 'memory', 'systems-programming', 'devops']
  },
  {
    id: 'res-tg-11',
    sourceType: 'TELEGRAM',
    externalId: 'tg_python2day_8155',
    title: 'Clearcam: Real-Time Computer Vision & Smart Monitoring with Python',
    description: 'Python script utility utilizing OpenCV, YOLO object detection, and local RTSP streaming for home security and smart automation.',
    resourceType: 'CODE',
    url: 'https://t.me/python2day/8155',
    canonicalUrl: 'https://t.me/python2day/8155',
    channel: 'python2day',
    stars: 0,
    forks: 0,
    publishedAt: '2026-09-01T12:00:00Z',
    discoveredAt: '2026-09-06T09:00:00Z',
    updatedAt: '2026-09-06T09:00:00Z',
    contentHash: 'hash_tg_py2day_8155',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 92.8,
    tags: ['python', 'opencv', 'computer-vision', 'automation', 'yolo']
  },
  {
    id: 'res-tg-12',
    sourceType: 'TELEGRAM',
    externalId: 'tg_python2day_8160',
    title: 'Antidetect Tools & Python Web Scraping Automation Defense',
    description: 'Comprehensive toolkit for managing browser fingerprints, rotating proxies, TLS fingerprint spoofing, and headless Chromium automation.',
    resourceType: 'TOOL',
    url: 'https://t.me/python2day/8160',
    canonicalUrl: 'https://t.me/python2day/8160',
    channel: 'python2day',
    stars: 0,
    forks: 0,
    publishedAt: '2026-09-02T15:00:00Z',
    discoveredAt: '2026-09-06T09:05:00Z',
    updatedAt: '2026-09-06T09:05:00Z',
    contentHash: 'hash_tg_py2day_8160',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 94.2,
    tags: ['python', 'web-scraping', 'automation', 'playwright', 'tools']
  },
  {
    id: 'res-tg-13',
    sourceType: 'TELEGRAM',
    externalId: 'tg_cs_resources_120',
    title: 'Computer Systems Architecture & Hardware-Software Interface',
    description: 'In-depth university course notes on superscalar processors, branch predictors, cache hierarchies, and assembly compilation.',
    resourceType: 'PDF',
    url: 'https://t.me/CS_Resources/120',
    canonicalUrl: 'https://t.me/cs_resources/120',
    channel: 'CS_Resources',
    fileName: 'Computer_Architecture_Notes.pdf',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    fileSize: 12582912,
    stars: 0,
    forks: 0,
    publishedAt: '2026-08-10T11:00:00Z',
    discoveredAt: '2026-09-05T08:00:00Z',
    updatedAt: '2026-09-05T08:00:00Z',
    contentHash: 'hash_tg_cs_120',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 95.0,
    tags: ['hardware', 'computer-architecture', 'cpu', 'assembly', 'pdf']
  },
  {
    id: 'res-tg-14',
    sourceType: 'TELEGRAM',
    externalId: 'tg_thedevs_1140',
    title: 'CSS Container Queries & Modern Responsive Layout Patterns',
    description: 'Detailed tutorial on container queries `@container`, subgrid, fluid typography with `clamp()`, and modern CSS without media queries.',
    resourceType: 'ARTICLE',
    url: 'https://t.me/thedevs/1140',
    canonicalUrl: 'https://t.me/thedevs/1140',
    channel: 'thedevs',
    stars: 0,
    forks: 0,
    publishedAt: '2026-08-20T17:00:00Z',
    discoveredAt: '2026-09-04T10:00:00Z',
    updatedAt: '2026-09-04T10:00:00Z',
    contentHash: 'hash_tg_thedevs_1140',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 91.5,
    tags: ['css', 'frontend', 'responsive-design', 'web-design', 'layout']
  },
  {
    id: 'res-tg-15',
    sourceType: 'TELEGRAM',
    externalId: 'tg_golang_news_1415',
    title: 'High-Performance Zero-Allocation JSON Parser for Go',
    description: 'Fast JSON parsing techniques in Go minimizing garbage collector pressure by avoiding heap allocations during payload decoding.',
    resourceType: 'LIBRARY',
    url: 'https://t.me/golang_news/1415',
    canonicalUrl: 'https://t.me/golang_news/1415',
    channel: 'golang_news',
    stars: 0,
    forks: 0,
    publishedAt: '2026-08-16T12:00:00Z',
    discoveredAt: '2026-09-03T16:00:00Z',
    updatedAt: '2026-09-03T16:00:00Z',
    contentHash: 'hash_tg_go_1415',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 92.1,
    tags: ['golang', 'json', 'performance', 'zero-allocation', 'library']
  },
  {
    id: 'res-tg-16',
    sourceType: 'TELEGRAM',
    externalId: 'tg_tech_interview_10',
    title: 'Dynamic Programming Patterns: 14 Must-Know Archetypes',
    description: 'Visual matrix and step-by-step recurrence relation formulas for Knapsack, Longest Common Subsequence, and Matrix Chain Multiplication.',
    resourceType: 'TUTORIAL',
    url: 'https://t.me/TechInterviewPrep/10',
    canonicalUrl: 'https://t.me/techinterviewprep/10',
    channel: 'TechInterviewPrep',
    stars: 0,
    forks: 0,
    publishedAt: '2026-08-05T09:00:00Z',
    discoveredAt: '2026-09-02T13:00:00Z',
    updatedAt: '2026-09-02T13:00:00Z',
    contentHash: 'hash_tg_interview_10',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 94.0,
    tags: ['algorithms', 'dynamic-programming', 'interview', 'faang', 'cheatsheet']
  },
  {
    id: 'res-tg-17',
    sourceType: 'TELEGRAM',
    externalId: 'tg_cybersecurity_hub_18',
    title: 'OWASP Top 10 API Security Risks & Mitigation Checklist',
    description: 'Practical security checklist for Broken Object Level Authorization (BOLA), mass assignment, unrestricted resource consumption, and JWT validation.',
    resourceType: 'DOCUMENTATION',
    url: 'https://t.me/cybersecurity_hub/18',
    canonicalUrl: 'https://t.me/cybersecurity_hub/18',
    channel: 'cybersecurity_hub',
    stars: 0,
    forks: 0,
    publishedAt: '2026-08-25T14:30:00Z',
    discoveredAt: '2026-09-01T15:00:00Z',
    updatedAt: '2026-09-01T15:00:00Z',
    contentHash: 'hash_tg_sec_18',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 95.2,
    tags: ['owasp', 'api-security', 'cybersecurity', 'jwt', 'checklist']
  },
  {
    id: 'res-tg-18',
    sourceType: 'TELEGRAM',
    externalId: 'tg_prog_notes_252',
    title: 'Microservices Event-Driven Architecture with Apache Kafka',
    description: 'Real-world guide on event sourcing, CQRS patterns, dead letter queues, and consumer group rebalancing in mission-critical systems.',
    resourceType: 'ARTICLE',
    url: 'https://t.me/programmers_notes/252',
    canonicalUrl: 'https://t.me/programmers_notes/252',
    channel: 'programmers_notes',
    stars: 0,
    forks: 0,
    publishedAt: '2026-09-01T11:00:00Z',
    discoveredAt: '2026-08-31T14:00:00Z',
    updatedAt: '2026-08-31T14:00:00Z',
    contentHash: 'hash_tg_notes_252',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 93.8,
    tags: ['kafka', 'microservices', 'event-driven', 'architecture', 'backend']
  },
  {
    id: 'res-tg-19',
    sourceType: 'TELEGRAM',
    externalId: 'tg_python2day_8150',
    title: 'Asynchronous Task Execution with Celery & Redis in Python',
    description: 'Production setup guide for distributed background tasks, rate limiting, task retries with exponential backoff, and flower monitoring.',
    resourceType: 'TUTORIAL',
    url: 'https://t.me/python2day/8150',
    canonicalUrl: 'https://t.me/python2day/8150',
    channel: 'python2day',
    stars: 0,
    forks: 0,
    publishedAt: '2026-08-27T10:00:00Z',
    discoveredAt: '2026-08-30T11:00:00Z',
    updatedAt: '2026-08-30T11:00:00Z',
    contentHash: 'hash_tg_py2day_8150',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 92.6,
    tags: ['python', 'celery', 'redis', 'async', 'tasks']
  },
  {
    id: 'res-tg-20',
    sourceType: 'TELEGRAM',
    externalId: 'tg_cs_resources_115',
    title: 'Discrete Mathematics and Graph Theory Reference Handbook',
    description: 'Illustrated guide covering graph coloring, shortest path algorithms, combinatorics, modular arithmetic, and cryptographic foundations.',
    resourceType: 'PDF',
    url: 'https://t.me/CS_Resources/115',
    canonicalUrl: 'https://t.me/cs_resources/115',
    channel: 'CS_Resources',
    fileName: 'Discrete_Math_Graph_Theory.pdf',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    fileSize: 18874368,
    stars: 0,
    forks: 0,
    publishedAt: '2026-08-01T09:00:00Z',
    discoveredAt: '2026-08-28T09:00:00Z',
    updatedAt: '2026-08-28T09:00:00Z',
    contentHash: 'hash_tg_cs_115',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: false,
    importanceScore: 94.5,
    tags: ['math', 'graph-theory', 'algorithms', 'cryptography', 'pdf']
  }
];

export const DEMO_COLLECTIONS: Collection[] = [
  {
    id: 'col-1',
    name: 'Python & FastAPI Arsenal',
    description: 'Production frameworks, automation tools, and async performance libraries for Python developers.',
    color: '#facc15',
    icon: 'Terminal',
    resourceCount: 8,
    createdAt: '2026-09-01T10:00:00Z',
    updatedAt: '2026-09-12T11:00:00Z'
  },
  {
    id: 'col-2',
    name: 'Machine Learning & AI Agents',
    description: 'From LangChain abstractions and AutoGPT to local Stable Diffusion web interfaces.',
    color: '#38bdf8',
    icon: 'Brain',
    resourceCount: 6,
    createdAt: '2026-09-08T14:30:00Z',
    updatedAt: '2026-09-11T16:00:00Z'
  },
  {
    id: 'col-3',
    name: 'Frontend Architect Toolkit',
    description: 'React, Next.js, Tailwind CSS, shadcn/ui, and bulletproof architecture patterns.',
    color: '#4ade80',
    icon: 'Layout',
    resourceCount: 6,
    createdAt: '2026-09-09T09:15:00Z',
    updatedAt: '2026-09-12T18:00:00Z'
  },
  {
    id: 'col-4',
    name: 'Computer Science & System Design',
    description: 'Database architecture textbooks, consensus algorithm lecture notes, and interview guides.',
    color: '#f87171',
    icon: 'Shield',
    resourceCount: 7,
    createdAt: '2026-09-05T12:00:00Z',
    updatedAt: '2026-09-10T19:00:00Z'
  }
];

export const DEMO_JOBS: ScraperJob[] = [
  {
    id: 'job-101',
    type: 'MANUAL_DISCOVERY',
    query: 'Python FastAPI and automation',
    sources: ['GITHUB', 'TELEGRAM'],
    status: 'COMPLETED',
    progress: 100,
    currentTask: 'All resources indexed and deduplicated.',
    resourcesFound: 32,
    duplicatesFound: 4,
    startedAt: '2026-09-13T07:45:00Z',
    completedAt: '2026-09-13T07:46:12Z',
    createdAt: '2026-09-13T07:44:50Z',
    logs: [
      { timestamp: '07:44:52', step: 'Initialization', message: 'Discovery job queued for GitHub and Telegram sources', type: 'info' },
      { timestamp: '07:45:00', step: 'GitHub Query', message: 'Discovered matching repositories on GitHub API', type: 'success' },
      { timestamp: '07:45:20', step: 'Telegram Channel Scrape', message: 'Scanned authorized public channels; extracted posts and PDFs', type: 'success' },
      { timestamp: '07:45:40', step: 'Deduplication', message: 'Deduplicated canonical URLs and generated content hashes', type: 'info' },
      { timestamp: '07:46:12', step: 'Completed', message: 'Indexed unique resources into local catalog', type: 'success' }
    ]
  },
  {
    id: 'job-102',
    type: 'SCHEDULED_DISCOVERY',
    query: 'React Next.js fullstack components',
    sources: ['GITHUB'],
    status: 'COMPLETED',
    progress: 100,
    currentTask: 'Indexed latest fullstack repositories.',
    resourcesFound: 18,
    duplicatesFound: 2,
    startedAt: '2026-09-13T08:15:00Z',
    completedAt: '2026-09-13T08:16:05Z',
    createdAt: '2026-09-13T08:14:30Z',
    schedule: 'DAILY',
    logs: [
      { timestamp: '08:14:30', step: 'Cron Trigger', message: 'Daily scheduled job started', type: 'info' },
      { timestamp: '08:15:00', step: 'GitHub Search', message: 'Fetched candidate repositories matching query', type: 'success' },
      { timestamp: '08:15:30', step: 'Metadata Harvest', message: 'Parsed repository README metadata & licenses', type: 'info' },
      { timestamp: '08:16:05', step: 'Completed', message: 'Updated resource index successfully', type: 'success' }
    ]
  }
];

export const DEMO_SOURCES: SourceConfig[] = [
  {
    id: 'src-gh',
    type: 'GITHUB',
    name: 'GitHub Official API',
    status: 'CONNECTED',
    lastSyncAt: '2026-09-13T08:15:00Z',
    resourceCount: 22,
    config: {
      authType: 'Official REST API v3',
      rateLimitRemaining: 4950,
      rateLimitTotal: 5000
    }
  },
  {
    id: 'src-tg',
    type: 'TELEGRAM',
    name: 'Telegram Public Channels Hub',
    status: 'CONNECTED',
    lastSyncAt: '2026-09-13T07:45:00Z',
    resourceCount: 20,
    config: {
      channelsMonitored: 8,
      authMode: 'Public Channel Web Gateway (t.me/s/)'
    }
  }
];

export const DEMO_SAVED_SEARCHES: SavedSearch[] = [
  {
    id: 'ss-1',
    query: 'Python AI agents',
    sources: ['GITHUB', 'TELEGRAM'],
    frequency: 'DAILY',
    notifyOnNew: true,
    lastRunAt: '2026-09-13T07:45:00Z',
    createdAt: '2026-09-01T10:00:00Z'
  },
  {
    id: 'ss-2',
    query: 'Rust high performance tools',
    sources: ['GITHUB'],
    frequency: 'WEEKLY',
    notifyOnNew: true,
    lastRunAt: '2026-09-10T12:00:00Z',
    createdAt: '2026-09-04T15:00:00Z'
  }
];

export const DEMO_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Discovery Job Completed',
    message: 'Found 32 new resources for query "Python FastAPI and automation".',
    type: 'SUCCESS',
    read: false,
    link: '/jobs',
    createdAt: '12 minutes ago'
  },
  {
    id: 'notif-2',
    title: 'Daily Saved Search Match',
    message: 'New high-star repositories matched your saved hunt "Python AI agents".',
    type: 'INFO',
    read: false,
    link: '/resources',
    createdAt: '2 hours ago'
  },
  {
    id: 'notif-3',
    title: 'Telegram Channel Synced',
    message: 'Extracted latest lecture notes & PDFs from @CS_Resources and @thedevs.',
    type: 'SUCCESS',
    read: true,
    link: '/sources',
    createdAt: 'Yesterday'
  }
];
