import { Resource, ScraperJob, Collection, SavedSearch, SourceConfig, NotificationItem } from '../types';

export const DEMO_RESOURCES: Resource[] = [
  // GitHub Resources
  {
    id: 'res-gh-1',
    sourceType: 'GITHUB',
    externalId: '101928371',
    title: 'Python Automation Toolkit & Script Arsenal',
    description: 'Battle-tested collection of 150+ production-ready Python automation scripts, web scrapers, task runners, and scheduled cron utilities with clean docstrings and CLI flags.',
    resourceType: 'REPOSITORY',
    url: 'https://github.com/the-comic-dev/python-automation-toolkit',
    canonicalUrl: 'https://github.com/the-comic-dev/python-automation-toolkit',
    author: 'the-comic-dev',
    owner: 'the-comic-dev',
    repository: 'python-automation-toolkit',
    language: 'Python',
    license: 'MIT',
    stars: 5420,
    forks: 874,
    publishedAt: '2026-03-12T10:00:00Z',
    discoveredAt: '2026-09-12T08:15:00Z',
    updatedAt: '2026-09-12T08:15:00Z',
    contentHash: 'a1b2c3d4e5f601',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: true,
    importanceScore: 94.5,
    tags: ['python', 'automation', 'productivity', 'cli', 'scripts'],
    readmePreview: `# Python Automation Toolkit\n\nCurated suite of automation tools for developers.\n\n## Quick Start\n\`\`\`bash\npip install comic-automator\ncomic-automator run --task sync\n\`\`\`\n\n## Features\n- Async background job scheduler\n- Robust PDF & CSV batch processing\n- Rate-limit aware API integration`
  },
  {
    id: 'res-gh-2',
    sourceType: 'GITHUB',
    externalId: '203948572',
    title: 'React 19 Clean SaaS Dashboard & UI Kit',
    description: 'Modern, highly accessible SaaS dashboard template built with React 19, Tailwind CSS, Lucide icons, and high-performance charting widgets.',
    resourceType: 'TEMPLATE',
    url: 'https://github.com/frontend-heroes/react-saas-dashboard-kit',
    canonicalUrl: 'https://github.com/frontend-heroes/react-saas-dashboard-kit',
    author: 'frontend-heroes',
    owner: 'frontend-heroes',
    repository: 'react-saas-dashboard-kit',
    language: 'TypeScript',
    license: 'Apache-2.0',
    stars: 8940,
    forks: 1420,
    publishedAt: '2026-02-18T14:30:00Z',
    discoveredAt: '2026-09-11T12:00:00Z',
    updatedAt: '2026-09-11T12:00:00Z',
    contentHash: 'b2c3d4e5f6a102',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: true,
    importanceScore: 98.2,
    tags: ['react', 'dashboard', 'typescript', 'tailwind', 'saas'],
    readmePreview: `# React 19 SaaS Dashboard Kit\n\nA full featured, production-ready SaaS dashboard.\n\n- Dark mode out of the box\n- 40+ prebuilt components\n- Accessible and mobile responsive`
  },
  {
    id: 'res-gh-3',
    sourceType: 'GITHUB',
    externalId: '304857291',
    title: 'Autonomous AI Agent Swarm Framework',
    description: 'Lightweight multi-agent orchestration architecture for orchestrating collaborative LLM workflows with deterministic memory and tool validation.',
    resourceType: 'LIBRARY',
    url: 'https://github.com/mindcraft/agent-swarm-core',
    canonicalUrl: 'https://github.com/mindcraft/agent-swarm-core',
    author: 'mindcraft',
    owner: 'mindcraft',
    repository: 'agent-swarm-core',
    language: 'Python',
    license: 'MIT',
    stars: 12340,
    forks: 2150,
    publishedAt: '2026-05-04T09:10:00Z',
    discoveredAt: '2026-09-13T04:20:00Z',
    updatedAt: '2026-09-13T04:20:00Z',
    contentHash: 'c3d4e5f6a1b203',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: true,
    importanceScore: 99.1,
    tags: ['ai-agents', 'llm', 'multi-agent', 'python', 'autonomous'],
    readmePreview: `# Autonomous Agent Swarm Core\n\nHigh-performance orchestration for multi-agent reasoning chains.`
  },
  {
    id: 'res-gh-4',
    sourceType: 'GITHUB',
    externalId: '405968172',
    title: 'Rust High-Speed Network Packet Sniffer & Inspector',
    description: 'Zero-copy high-throughput network monitoring and packet analysis CLI tool written in Rust with PCAP export and terminal UI dashboard.',
    resourceType: 'TOOL',
    url: 'https://github.com/rust-sec/packet-hound',
    canonicalUrl: 'https://github.com/rust-sec/packet-hound',
    author: 'rust-sec',
    owner: 'rust-sec',
    repository: 'packet-hound',
    language: 'Rust',
    license: 'GPL-3.0',
    stars: 3870,
    forks: 310,
    publishedAt: '2026-01-22T16:45:00Z',
    discoveredAt: '2026-09-10T11:05:00Z',
    updatedAt: '2026-09-10T11:05:00Z',
    contentHash: 'd4e5f6a1b2c304',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: true,
    importanceScore: 88.4,
    tags: ['rust', 'networking', 'security', 'cybersecurity', 'cli'],
    readmePreview: `# Packet Hound (Rust)\n\nFast network analysis and packet stream inspection.`
  },
  {
    id: 'res-gh-5',
    sourceType: 'GITHUB',
    externalId: '506978283',
    title: 'Full-Stack Machine Learning Engineering Handbook',
    description: 'Curated curriculum, architectural diagrams, model deployment pipelines, and end-to-end MLOps production blueprints.',
    resourceType: 'DOCUMENTATION',
    url: 'https://github.com/ml-mastery/mlops-handbook',
    canonicalUrl: 'https://github.com/ml-mastery/mlops-handbook',
    author: 'ml-mastery',
    owner: 'ml-mastery',
    repository: 'mlops-handbook',
    language: 'Jupyter Notebook',
    license: 'CC-BY-4.0',
    stars: 18200,
    forks: 4320,
    publishedAt: '2025-11-10T12:00:00Z',
    discoveredAt: '2026-09-09T15:30:00Z',
    updatedAt: '2026-09-09T15:30:00Z',
    contentHash: 'e5f6a1b2c3d405',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: true,
    importanceScore: 97.8,
    tags: ['machine-learning', 'mlops', 'data-science', 'python', 'handbook'],
    readmePreview: `# Full-Stack ML Engineering Handbook\n\nComplete guide to training, testing, and serving AI models at scale.`
  },
  {
    id: 'res-gh-6',
    sourceType: 'GITHUB',
    externalId: '607898394',
    title: 'Go Microservices Boilerplate with gRPC & Observability',
    description: 'Production-grade enterprise Go microservices template featuring OpenTelemetry tracing, Prometheus metrics, structured logging, and Kubernetes manifests.',
    resourceType: 'CODE',
    url: 'https://github.com/gophers-guild/go-grpc-microservices-starter',
    canonicalUrl: 'https://github.com/gophers-guild/go-grpc-microservices-starter',
    author: 'gophers-guild',
    owner: 'gophers-guild',
    repository: 'go-grpc-microservices-starter',
    language: 'Go',
    license: 'MIT',
    stars: 4620,
    forks: 780,
    publishedAt: '2026-04-11T09:00:00Z',
    discoveredAt: '2026-09-11T16:10:00Z',
    updatedAt: '2026-09-11T16:10:00Z',
    contentHash: 'f6a1b2c3d4e506',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: true,
    importanceScore: 89.3,
    tags: ['go', 'grpc', 'microservices', 'kubernetes', 'opentelemetry'],
    readmePreview: `# Go Microservices Boilerplate\n\nCloud-native foundation for resilient Go backends.`
  },
  {
    id: 'res-gh-7',
    sourceType: 'GITHUB',
    externalId: '708901405',
    title: 'Modern Web Scraping Ninja Guide & Playwright Examples',
    description: 'Comprehensive repository covering ethical scraping patterns, dynamic rendering, proxy rotation, and anti-bot mitigation strategies using Playwright and TypeScript.',
    resourceType: 'TUTORIAL',
    url: 'https://github.com/scraping-ninja/playwright-scraper-patterns',
    canonicalUrl: 'https://github.com/scraping-ninja/playwright-scraper-patterns',
    author: 'scraping-ninja',
    owner: 'scraping-ninja',
    repository: 'playwright-scraper-patterns',
    language: 'TypeScript',
    license: 'MIT',
    stars: 6730,
    forks: 940,
    publishedAt: '2026-03-29T18:20:00Z',
    discoveredAt: '2026-09-12T13:40:00Z',
    updatedAt: '2026-09-12T13:40:00Z',
    contentHash: 'a2b3c4d5e6f707',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: true,
    importanceScore: 92.6,
    tags: ['web-scraping', 'playwright', 'crawler', 'typescript', 'tutorial'],
    readmePreview: `# Playwright Scraper Patterns\n\nMaster enterprise web data collection with clean TypeScript practices.`
  },
  {
    id: 'res-gh-8',
    sourceType: 'GITHUB',
    externalId: '809012516',
    title: 'DevOps & SRE Interview Questions with Deep Architectural Dives',
    description: '1000+ categorized DevOps, Linux internals, Kubernetes, Terraform, and CI/CD interview scenarios with verified solutions and architecture diagrams.',
    resourceType: 'EBOOK',
    url: 'https://github.com/sre-master/devops-interview-bible',
    canonicalUrl: 'https://github.com/sre-master/devops-interview-bible',
    author: 'sre-master',
    owner: 'sre-master',
    repository: 'devops-interview-bible',
    language: 'Markdown',
    license: 'CC0-1.0',
    stars: 15400,
    forks: 3600,
    publishedAt: '2026-01-05T11:00:00Z',
    discoveredAt: '2026-09-08T19:25:00Z',
    updatedAt: '2026-09-08T19:25:00Z',
    contentHash: 'b3c4d5e6f7a208',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: true,
    importanceScore: 95.0,
    tags: ['devops', 'kubernetes', 'sre', 'interview', 'study-guide'],
    readmePreview: `# DevOps Interview Bible\n\nDeep technical breakdowns of distributed systems and operations.`
  },
  {
    id: 'res-gh-9',
    sourceType: 'GITHUB',
    externalId: '910123627',
    title: 'FastAPI Microservice Template with Async SQLAlchemy 2.0',
    description: 'Plug-and-play FastAPI template with async PostgreSQL engine, Alembic migrations, Redis cache invalidation, and JWT authentication.',
    resourceType: 'CODE',
    url: 'https://github.com/tiangolo-fans/fastapi-clean-architecture',
    canonicalUrl: 'https://github.com/tiangolo-fans/fastapi-clean-architecture',
    author: 'tiangolo-fans',
    owner: 'tiangolo-fans',
    repository: 'fastapi-clean-architecture',
    language: 'Python',
    license: 'MIT',
    stars: 7890,
    forks: 1120,
    publishedAt: '2026-05-15T08:15:00Z',
    discoveredAt: '2026-09-12T22:10:00Z',
    updatedAt: '2026-09-12T22:10:00Z',
    contentHash: 'c4d5e6f7a2b309',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: true,
    importanceScore: 93.7,
    tags: ['python', 'fastapi', 'sqlalchemy', 'rest-api', 'clean-architecture'],
    readmePreview: `# FastAPI Clean Architecture\n\nEnterprise-grade starter project for modern async Python APIs.`
  },
  {
    id: 'res-gh-10',
    sourceType: 'GITHUB',
    externalId: '102134738',
    title: 'Prompt Engineering & LLM Jailbreak Defense Benchmark Dataset',
    description: 'Systematic dataset containing 5,000+ annotated adversarial prompts and mitigation defenses for safety alignment in generative AI models.',
    resourceType: 'DATASET',
    url: 'https://github.com/ai-safety-bench/prompt-injection-defense-corpus',
    canonicalUrl: 'https://github.com/ai-safety-bench/prompt-injection-defense-corpus',
    author: 'ai-safety-bench',
    owner: 'ai-safety-bench',
    repository: 'prompt-injection-defense-corpus',
    language: 'Python',
    license: 'MIT',
    stars: 3410,
    forks: 420,
    publishedAt: '2026-06-01T14:50:00Z',
    discoveredAt: '2026-09-13T01:45:00Z',
    updatedAt: '2026-09-13T01:45:00Z',
    contentHash: 'd5e6f7a2b3c410',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: true,
    importanceScore: 87.9,
    tags: ['dataset', 'ai-safety', 'prompt-engineering', 'security', 'llm'],
    readmePreview: `# Prompt Injection Defense Corpus\n\nBenchmark dataset for testing AI robustness against input manipulation.`
  },

  // Telegram Resources
  {
    id: 'res-tg-1',
    sourceType: 'TELEGRAM',
    externalId: 'tg_msg_90112',
    title: 'Python Complete Automation & Scripting Cheatsheet',
    description: 'Comprehensive 42-page visual cheatsheet covering OS manipulation, subprocesses, regular expressions, BeautifulSoup, and Requests.',
    resourceType: 'PDF',
    url: 'https://t.me/PythonResourcesDaily/90112',
    canonicalUrl: 'https://t.me/PythonResourcesDaily/90112',
    author: 'Python Resources Daily',
    channel: 'PythonResourcesDaily',
    fileName: 'Python_Automation_Cheatsheet_v4.pdf',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    fileSize: 8808038, // 8.4 MB
    stars: 0,
    forks: 0,
    publishedAt: '2026-09-12T11:20:00Z',
    discoveredAt: '2026-09-12T11:35:00Z',
    updatedAt: '2026-09-12T11:35:00Z',
    contentHash: 'e6f7a2b3c4d511',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: true,
    importanceScore: 91.2,
    tags: ['python', 'pdf', 'cheatsheet', 'automation', 'notes']
  },
  {
    id: 'res-tg-2',
    sourceType: 'TELEGRAM',
    externalId: 'tg_msg_90113',
    title: 'Deep Learning with PyTorch: Lecture Notes & Code Snippets',
    description: 'Annotated university lecture slides covering backpropagation, Transformers, attention mechanisms, and fine-tuning LoRA adapters.',
    resourceType: 'PDF',
    url: 'https://t.me/AIDataScienceHub/4120',
    canonicalUrl: 'https://t.me/AIDataScienceHub/4120',
    author: 'AI Data Science Hub',
    channel: 'AIDataScienceHub',
    fileName: 'PyTorch_Deep_Learning_Master_Notes.pdf',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    fileSize: 15728640, // 15 MB
    stars: 0,
    forks: 0,
    publishedAt: '2026-09-11T14:15:00Z',
    discoveredAt: '2026-09-11T14:40:00Z',
    updatedAt: '2026-09-11T14:40:00Z',
    contentHash: 'f7a2b3c4d5e612',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: true,
    importanceScore: 93.0,
    tags: ['pytorch', 'deep-learning', 'pdf', 'transformers', 'ai']
  },
  {
    id: 'res-tg-3',
    sourceType: 'TELEGRAM',
    externalId: 'tg_msg_90114',
    title: 'Cybersecurity Red Team Field Kit & Exploitation Mindmap',
    description: 'Vector PDF mindmap detailing active directory persistence, privilege escalation techniques, and lateral movement evasion tactics.',
    resourceType: 'PDF',
    url: 'https://t.me/CyberSecNotesArchive/1589',
    canonicalUrl: 'https://t.me/CyberSecNotesArchive/1589',
    author: 'CyberSec Notes Archive',
    channel: 'CyberSecNotesArchive',
    fileName: 'Red_Team_Field_Playbook_2026.pdf',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    fileSize: 6291456, // 6 MB
    stars: 0,
    forks: 0,
    publishedAt: '2026-09-10T19:00:00Z',
    discoveredAt: '2026-09-10T19:15:00Z',
    updatedAt: '2026-09-10T19:15:00Z',
    contentHash: 'a3b4c5d6e7f813',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: true,
    importanceScore: 89.8,
    tags: ['cybersecurity', 'infosec', 'pdf', 'redteam', 'pentest']
  },
  {
    id: 'res-tg-4',
    sourceType: 'TELEGRAM',
    externalId: 'tg_msg_90115',
    title: 'System Design Interview: 25 Real-World Case Studies',
    description: 'Step-by-step breakdowns of high-scale architectures: Designing YouTube, Uber, TinyURL, distributed caches, and rate limiters.',
    resourceType: 'EBOOK',
    url: 'https://t.me/TechInterviewPrep/3044',
    canonicalUrl: 'https://t.me/TechInterviewPrep/3044',
    author: 'Tech Interview Prep',
    channel: 'TechInterviewPrep',
    fileName: 'System_Design_Case_Studies_Compendium.epub',
    fileExtension: 'epub',
    mimeType: 'application/epub+zip',
    fileSize: 11534336, // 11 MB
    stars: 0,
    forks: 0,
    publishedAt: '2026-09-09T08:30:00Z',
    discoveredAt: '2026-09-09T09:00:00Z',
    updatedAt: '2026-09-09T09:00:00Z',
    contentHash: 'b4c5d6e7f8a314',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: true,
    importanceScore: 96.5,
    tags: ['system-design', 'architecture', 'interview', 'scalability', 'ebook']
  },
  {
    id: 'res-tg-5',
    sourceType: 'TELEGRAM',
    externalId: 'tg_msg_90116',
    title: 'Docker & Kubernetes Offline Reference Archives',
    description: 'Offline bundle containing HTML documentation mirrors, configuration snippets, and Helm charts for air-gapped deployments.',
    resourceType: 'ZIP',
    url: 'https://t.me/DevOpsVault/821',
    canonicalUrl: 'https://t.me/DevOpsVault/821',
    author: 'DevOps Vault',
    channel: 'DevOpsVault',
    fileName: 'k8s_docker_offline_docs_bundle.zip',
    fileExtension: 'zip',
    mimeType: 'application/zip',
    fileSize: 33554432, // 32 MB
    stars: 0,
    forks: 0,
    publishedAt: '2026-09-08T16:20:00Z',
    discoveredAt: '2026-09-08T16:50:00Z',
    updatedAt: '2026-09-08T16:50:00Z',
    contentHash: 'c5d6e7f8a3b415',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: true,
    importanceScore: 86.7,
    tags: ['kubernetes', 'docker', 'zip', 'devops', 'offline-docs']
  },
  {
    id: 'res-tg-6',
    sourceType: 'TELEGRAM',
    externalId: 'tg_msg_90117',
    title: 'Frontend Performance Optimization Master Checklist',
    description: 'Detailed interactive guide on Core Web Vitals, LCP reduction, font loading strategies, and critical CSS inlining.',
    resourceType: 'ARTICLE',
    url: 'https://t.me/FrontendDevelopersFeed/5540',
    canonicalUrl: 'https://t.me/FrontendDevelopersFeed/5540',
    author: 'Frontend Developers Feed',
    channel: 'FrontendDevelopersFeed',
    stars: 0,
    forks: 0,
    publishedAt: '2026-09-12T18:00:00Z',
    discoveredAt: '2026-09-12T18:30:00Z',
    updatedAt: '2026-09-12T18:30:00Z',
    contentHash: 'd6e7f8a3b4c516',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: true,
    importanceScore: 90.4,
    tags: ['frontend', 'performance', 'web-vitals', 'javascript', 'tutorial']
  },
  {
    id: 'res-tg-7',
    sourceType: 'TELEGRAM',
    externalId: 'tg_msg_90118',
    title: 'SQL Query Tuning & Postgres Indexing Deep Dive',
    description: 'Practical handbook on B-Tree vs GIN vs BRIN indexes, EXPLAIN ANALYZE execution plans, and resolving slow queries.',
    resourceType: 'TUTORIAL',
    url: 'https://t.me/DatabaseInternals/2110',
    canonicalUrl: 'https://t.me/DatabaseInternals/2110',
    author: 'Database Internals Channel',
    channel: 'DatabaseInternals',
    fileName: 'Postgres_Performance_Optimization_Guide.pdf',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    fileSize: 4718592, // 4.5 MB
    stars: 0,
    forks: 0,
    publishedAt: '2026-09-07T12:10:00Z',
    discoveredAt: '2026-09-07T12:45:00Z',
    updatedAt: '2026-09-07T12:45:00Z',
    contentHash: 'e7f8a3b4c5d617',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: true,
    importanceScore: 94.1,
    tags: ['postgresql', 'sql', 'database', 'performance', 'pdf']
  },
  {
    id: 'res-tg-8',
    sourceType: 'TELEGRAM',
    externalId: 'tg_msg_90119',
    title: 'Go (Golang) Concurrency Patterns with Channels & Goroutines',
    description: 'Visual code walkthroughs of fan-in, fan-out, pipeline processing, and context cancellation patterns with race condition prevention.',
    resourceType: 'CODE',
    url: 'https://t.me/GoDevelopersWorld/789',
    canonicalUrl: 'https://t.me/GoDevelopersWorld/789',
    author: 'Go Developers World',
    channel: 'GoDevelopersWorld',
    fileName: 'golang_concurrency_patterns.go',
    fileExtension: 'go',
    mimeType: 'text/x-go',
    fileSize: 45056,
    stars: 0,
    forks: 0,
    publishedAt: '2026-09-06T10:00:00Z',
    discoveredAt: '2026-09-06T10:20:00Z',
    updatedAt: '2026-09-06T10:20:00Z',
    contentHash: 'f8a3b4c5d6e718',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: true,
    importanceScore: 88.7,
    tags: ['go', 'golang', 'concurrency', 'patterns', 'code']
  },
  {
    id: 'res-tg-9',
    sourceType: 'TELEGRAM',
    externalId: 'tg_msg_90120',
    title: 'Complete Free E-Books Collection for Data Scientists',
    description: 'Direct download links and verified mirror hashes for 30 open-access statistics, machine learning, and linear algebra textbooks.',
    resourceType: 'LINK',
    url: 'https://t.me/DataScienceLibrary/1420',
    canonicalUrl: 'https://t.me/DataScienceLibrary/1420',
    author: 'Data Science Library',
    channel: 'DataScienceLibrary',
    stars: 0,
    forks: 0,
    publishedAt: '2026-09-05T14:40:00Z',
    discoveredAt: '2026-09-05T15:00:00Z',
    updatedAt: '2026-09-05T15:00:00Z',
    contentHash: 'a4b5c6d7e8f919',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: true,
    importanceScore: 92.3,
    tags: ['data-science', 'ebook', 'math', 'statistics', 'links']
  },
  {
    id: 'res-tg-10',
    sourceType: 'TELEGRAM',
    externalId: 'tg_msg_90121',
    title: 'FastAPI + Docker Security Best Practices Cheat Sheet',
    description: 'Summary of non-root container configuration, multi-stage builds, CORS hardening, and rate limiting middlewares.',
    resourceType: 'PDF',
    url: 'https://t.me/PythonSecurityGroup/632',
    canonicalUrl: 'https://t.me/PythonSecurityGroup/632',
    author: 'Python Security Group',
    channel: 'PythonSecurityGroup',
    fileName: 'FastAPI_Docker_Hardening_CheatSheet.pdf',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    fileSize: 2097152, // 2 MB
    stars: 0,
    forks: 0,
    publishedAt: '2026-09-12T09:15:00Z',
    discoveredAt: '2026-09-12T09:30:00Z',
    updatedAt: '2026-09-12T09:30:00Z',
    contentHash: 'b5c6d7e8f9a420',
    dedupeScore: 0.0,
    isDuplicate: false,
    isDemo: true,
    importanceScore: 91.8,
    tags: ['fastapi', 'docker', 'security', 'python', 'pdf']
  }
];

export const DEMO_COLLECTIONS: Collection[] = [
  {
    id: 'col-1',
    name: 'Python Automation & Tooling',
    description: 'Curated repositories, scripts, and PDF cheat sheets for automating developer workflows.',
    color: '#facc15',
    icon: 'Terminal',
    resourceCount: 5,
    createdAt: '2026-09-10T10:00:00Z',
    updatedAt: '2026-09-12T11:00:00Z'
  },
  {
    id: 'col-2',
    name: 'Machine Learning & MLOps',
    description: 'Everything from theoretical Transformers to production Kubernetes deployments.',
    color: '#38bdf8',
    icon: 'Brain',
    resourceCount: 4,
    createdAt: '2026-09-08T14:30:00Z',
    updatedAt: '2026-09-11T16:00:00Z'
  },
  {
    id: 'col-3',
    name: 'Frontend Architect Toolkit',
    description: 'React 19 templates, component systems, and Web Vitals optimization guides.',
    color: '#4ade80',
    icon: 'Layout',
    resourceCount: 3,
    createdAt: '2026-09-09T09:15:00Z',
    updatedAt: '2026-09-12T18:00:00Z'
  },
  {
    id: 'col-4',
    name: 'Cybersecurity & Red Team Notes',
    description: 'Penetration testing guides, exploit mitigation, and audit mindmaps.',
    color: '#f87171',
    icon: 'Shield',
    resourceCount: 3,
    createdAt: '2026-09-05T12:00:00Z',
    updatedAt: '2026-09-10T19:00:00Z'
  }
];

export const DEMO_JOBS: ScraperJob[] = [
  {
    id: 'job-101',
    type: 'MANUAL_DISCOVERY',
    query: 'Python machine learning',
    sources: ['GITHUB', 'TELEGRAM'],
    status: 'COMPLETED',
    progress: 100,
    currentTask: 'All resources indexed and deduplicated.',
    resourcesFound: 48,
    duplicatesFound: 6,
    startedAt: '2026-09-13T07:45:00Z',
    completedAt: '2026-09-13T07:46:12Z',
    createdAt: '2026-09-13T07:44:50Z',
    logs: [
      { timestamp: '07:44:52', step: 'Initialization', message: 'Discovery job queued for GitHub and Telegram sources', type: 'info' },
      { timestamp: '07:45:00', step: 'GitHub Query', message: 'Discovered 28 matching repositories on GitHub API', type: 'success' },
      { timestamp: '07:45:20', step: 'Telegram Channel Scrape', message: 'Scanned 4 authorized public channels; found 20 posts with media', type: 'success' },
      { timestamp: '07:45:40', step: 'Deduplication', message: 'Detected 6 duplicate canonical URLs with confidence >0.85', type: 'info' },
      { timestamp: '07:46:12', step: 'Completed', message: 'Indexed 48 unique resources into local catalog', type: 'success' }
    ]
  },
  {
    id: 'job-102',
    type: 'SCHEDULED_DISCOVERY',
    query: 'React dashboard templates',
    sources: ['GITHUB'],
    status: 'RUNNING',
    progress: 68,
    currentTask: 'Parsing repository README metadata & licenses...',
    resourcesFound: 24,
    duplicatesFound: 2,
    startedAt: '2026-09-13T08:15:00Z',
    createdAt: '2026-09-13T08:14:30Z',
    schedule: 'DAILY',
    logs: [
      { timestamp: '08:14:30', step: 'Cron Trigger', message: 'Daily scheduled job started', type: 'info' },
      { timestamp: '08:15:00', step: 'GitHub Search', message: 'Fetched 30 candidate repositories matching query', type: 'success' },
      { timestamp: '08:15:30', step: 'Metadata Harvest', message: 'Parsing repository README metadata & licenses...', type: 'info' }
    ]
  },
  {
    id: 'job-103',
    type: 'SOURCE_SYNC',
    query: 'Authorized Channel Sync',
    sources: ['TELEGRAM'],
    status: 'QUEUED',
    progress: 0,
    currentTask: 'Waiting in worker queue...',
    resourcesFound: 0,
    duplicatesFound: 0,
    createdAt: '2026-09-13T08:20:00Z',
    logs: [
      { timestamp: '08:20:00', step: 'Queueing', message: 'Job scheduled by user', type: 'info' }
    ]
  }
];

export const DEMO_SOURCES: SourceConfig[] = [
  {
    id: 'src-gh',
    type: 'GITHUB',
    name: 'GitHub Official API',
    status: 'CONNECTED',
    lastSyncAt: '2026-09-13T08:15:00Z',
    resourceCount: 14280,
    config: {
      authType: 'Public + Personal Token',
      rateLimitRemaining: 4920,
      rateLimitTotal: 5000
    }
  },
  {
    id: 'src-tg',
    type: 'TELEGRAM',
    name: 'Telegram Public & Authorized Hub',
    status: 'CONNECTED',
    lastSyncAt: '2026-09-13T07:45:00Z',
    resourceCount: 8640,
    config: {
      channelsMonitored: 8,
      authMode: 'Public Channel Web Reader + Bot API'
    }
  }
];

export const DEMO_SAVED_SEARCHES: SavedSearch[] = [
  {
    id: 'ss-1',
    query: 'Python AI agents',
    sources: ['GITHUB', 'TELEGRAM'],
    frequency: 'DAILY',
    notifyOnNew: true,
    lastRunAt: '2026-09-13T07:45:00Z',
    createdAt: '2026-09-01T10:00:00Z'
  },
  {
    id: 'ss-2',
    query: 'Rust network tools',
    sources: ['GITHUB'],
    frequency: 'WEEKLY',
    notifyOnNew: true,
    lastRunAt: '2026-09-10T12:00:00Z',
    createdAt: '2026-09-04T15:00:00Z'
  }
];

export const DEMO_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Discovery Job Completed',
    message: 'Found 48 new resources for query "Python machine learning".',
    type: 'SUCCESS',
    read: false,
    link: '/jobs',
    createdAt: '12 minutes ago'
  },
  {
    id: 'notif-2',
    title: 'Daily Saved Search Match',
    message: '3 new repositories matched your saved hunt "Python AI agents".',
    type: 'INFO',
    read: false,
    link: '/resources',
    createdAt: '2 hours ago'
  },
  {
    id: 'notif-3',
    title: 'Telegram Channel Synced',
    message: '8 new documents & PDFs extracted from @PythonResourcesDaily.',
    type: 'SUCCESS',
    read: true,
    link: '/sources',
    createdAt: 'Yesterday'
  }
];
